### ISSUE TITLE
Project is not open source without a license file

### ISSUE THREAD

**Issue by karan** [araqne/core#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by xeraph** [comment]
Each source file has a license terms at top position. All araqne project are licensed under apache software license 2 by default.

**Comment by karan** [comment]
Thanks
